export const surveyJsonKz = {
    showProgressBar: "top",
    progressBarType: "questions",
    pageNextText: "Келесі",
    pagePrevText: "Артқа",
    completeText: "Жіберу",

    pages: [
        {
            name: "demographics",
            elements: [
                {
                    type: "dropdown",
                    name: "отдел",
                    title: "Бөлімді таңдаңыз",
                    isRequired: true,
                    placeholder: "Бөлімді таңдаңыз",
                    choices: [
                        {
                            value: "Отдел кардиохирургии с реабилитацией",
                            text: "Оңалтумен кардиохирургия бөлімі",
                        },
                        {
                            value: "Отдел интервенционной кардиологии № 1",
                            text: "№1 интервенциялық кардиология бөлімі",
                        },
                        {
                            value: "Отдел интервенционной кардиологии № 2",
                            text: "№2 интервенциялық кардиология бөлімі",
                        },
                        {
                            value: "Отдел гинекологии",
                            text: "Гинекология бөлімі",
                        },
                        {
                            value: "Отдел аритмологии",
                            text: "Аритмология бөлімі",
                        },
                        {
                            value: "Отдел терапии №2",
                            text: "№2 терапия бөлімі",
                        },
                        {
                            value: "Отдел общей и торакальной хирургии",
                            text: "Жалпы және кеуде хирургиясы бөлімі",
                        },
                        {
                            value: "Отдел нейрохирургии",
                            text: "Нейрохирургия бөлімі",
                        },
                        {
                            value: "Отдел урологии",
                            text: "Урология бөлімі",
                        },
                        {
                            value: "Детский кардиохирургический центр",
                            text: "Балалар кардиохирургиялық орталығы",
                        },
                    ],
                },
                {
                    type: "radiogroup",
                    name: "пол",
                    title: "Жынысыңыз",
                    isRequired: true,
                    colCount: 2,
                    choices: ["Еркек", "Әйел"],
                },
                {
                    type: "radiogroup",
                    name: "возраст",
                    title: "Жасыңыз",
                    isRequired: true,
                    colCount: 3,
                    choices: [
                        "15-тен кем",
                        "16-30 жас",
                        "31-40 жас",
                        "41-50 жас",
                        "51-60 жас",
                        "60-тан астам",
                    ],
                },
            ],
        },
        {
            name: "service",
            title: "Қызмет көрсету жеделдігі",
            elements: [
                {
                    type: "rating",
                    name: "Регистратура",
                    title: "Тіркеу бөлімінің жұмысын бағалаңыз",
                    isRequired: true,
                    rateCount: 10,
                    rateMin: 1,
                    rateMax: 10,
                    defaultValue: 10,
                    minRateDescription: "Нашар",
                    maxRateDescription: "Өте жақсы",
                },
                {
                    type: "rating",
                    name: "Лечебный отдел",
                    title: "Емдеу бөлімінің жұмысын бағалаңыз",
                    isRequired: true,
                    rateCount: 10,
                    rateMin: 1,
                    rateMax: 10,
                    defaultValue: 10,
                },
                {
                    type: "rating",
                    name: "Приемный отдел",
                    title: "Қабылдау бөлімінің жұмысын бағалаңыз",
                    isRequired: true,
                    rateCount: 10,
                    rateMin: 1,
                    rateMax: 10,
                    defaultValue: 10,
                },
                {
                    type: "rating",
                    name: "Диагностический отдел",
                    title: "Диагностикалық бөлімдердің жұмысын бағалаңыз",
                    isRequired: true,
                    rateCount: 10,
                    rateMin: 1,
                    rateMax: 10,
                    defaultValue: 10,
                },
            ],
        },
        {
            name: "staff",
            title: "Персоналдың жұмыс сапасы",
            elements: [
                {
                    type: "rating",
                    name: "Лечащего врача",
                    title: "Емдеуші дәрігердің жұмысын бағалаңыз",
                    isRequired: true,
                    rateCount: 10,
                    rateMin: 1,
                    rateMax: 10,
                    defaultValue: 10,
                },
                {
                    type: "rating",
                    name: "Дежурного врача",
                    title: "Кезекші дәрігердің жұмысын бағалаңыз",
                    isRequired: true,
                    rateCount: 10,
                    rateMin: 1,
                    rateMax: 10,
                    defaultValue: 10,
                },
                {
                    type: "rating",
                    name: "Медицинской сестры",
                    title: "Медбикенің жұмысын бағалаңыз",
                    isRequired: true,
                    rateCount: 10,
                    rateMin: 1,
                    rateMax: 10,
                    defaultValue: 10,
                },
                {
                    type: "rating",
                    name: "Младшего мед персонала",
                    title: "Кіші медперсоналдың жұмысын бағалаңыз",
                    isRequired: true,
                    rateCount: 10,
                    rateMin: 1,
                    rateMax: 10,
                    defaultValue: 10,
                },
            ],
        },
        {
            name: "attitude",
            title: "Сыпайылық және ілтипаттылық",
            elements: [
                {
                    type: "rating",
                    name: "Вежливость врача",
                    title: "Дәрігердің сыпайылығы мен ілтипаттылығы",
                    isRequired: true,
                    rateCount: 10,
                    rateMin: 1,
                    rateMax: 10,
                    defaultValue: 10,
                },
                {
                    type: "rating",
                    name: "Вежливость медсестры",
                    title: "Медбикенің сыпайылығы мен ілтипаттылығы",
                    isRequired: true,
                    rateCount: 10,
                    rateMin: 1,
                    rateMax: 10,
                    defaultValue: 10,
                },
                {
                    type: "rating",
                    name: "Информирование",
                    title: "Процедуралар алдындағы ақпараттандыру толықтығы",
                    isRequired: true,
                    rateCount: 10,
                    rateMin: 1,
                    rateMax: 10,
                    defaultValue: 10,
                },
                {
                    type: "rating",
                    name: "Рекомендации при выписке",
                    title: "Шығару кезіндегі ұсыныстардың сапасы",
                    isRequired: true,
                    rateCount: 10,
                    rateMin: 1,
                    rateMax: 10,
                    defaultValue: 10,
                },
            ],
        },
        {
            name: "facilities",
            title: "Тұру жағдайлары",
            elements: [
                {
                    type: "rating",
                    name: "Качество питания",
                    title: "Тамақтандыру сапасын бағалаңыз",
                    isRequired: true,
                    rateCount: 10,
                    rateMin: 1,
                    rateMax: 10,
                    defaultValue: 10,
                },
                {
                    type: "rating",
                    name: "Внешний вид персонала",
                    title: "Персоналдың сыртқы түрін бағалаңыз",
                    isRequired: true,
                    rateCount: 10,
                    rateMin: 1,
                    rateMax: 10,
                    defaultValue: 10,
                },
                {
                    type: "rating",
                    name: "Сервисные услуги",
                    title: "Сервисті бағалаңыз (тазалық, тұрақ, күзет)",
                    isRequired: true,
                    rateCount: 10,
                    rateMin: 1,
                    rateMax: 10,
                    defaultValue: 10,
                },
            ],
        },
        {
            name: "overall",
            title: "Жалпы баға",
            elements: [
                {
                    type: "rating",
                    name: "Рекомендация клиники",
                    title: "Клиниканы ұсынуға дайынсыз ба?",
                    isRequired: true,
                    rateCount: 10,
                    rateMin: 1,
                    rateMax: 10,
                    defaultValue: 10,
                },
                {
                    type: "rating",
                    name: "Общая удовлетворенность",
                    title: "Клиникаға жалпы қанағаттану",
                    isRequired: true,
                    rateCount: 10,
                    rateMin: 1,
                    rateMax: 10,
                    defaultValue: 10,
                },
                {
                    type: "radiogroup",
                    name: "Сравнение с другими",
                    title: "Клиниканы басқалармен салыстырғанда қалай бағалайсыз?",
                    isRequired: true,
                    defaultValue: "Басқалардан жақсы",
                    choices: [
                        "Басқалардан жақсы",
                        "Бірдей",
                        "Басқалардан нашар",
                        "Білмеймін",
                    ],
                },
            ],
        },
        {
            name: "yesno",
            title: "Қосымша сұрақтар",
            elements: [
                {
                    type: "radiogroup",
                    name: "Выбор врача",
                    title: "Дәрігерді таңдау мүмкіндігі болды ма?",
                    isRequired: true,
                    defaultValue: "Иә",
                    choices: ["Иә", "Жоқ", "Жауап беру қиын"],
                },
                {
                    type: "radiogroup",
                    name: "Конфиденциальность",
                    title: "Құпиялылық сақталды ма?",
                    isRequired: true,
                    defaultValue: "Иә",
                    choices: ["Иә", "Жоқ", "Жауап беру қиын"],
                },
                {
                    type: "radiogroup",
                    name: "Согласие на лечение",
                    title: "Емдеуге келісіміңіз алынды ма?",
                    isRequired: true,
                    defaultValue: "Иә",
                    choices: ["Иә", "Жоқ", "Жауап беру қиын"],
                },
                {
                    type: "radiogroup",
                    name: "Гигиена рук",
                    title: "Медқызметкер қарау алдында қолын жуды ма?",
                    isRequired: true,
                    defaultValue: "Иә",
                    choices: ["Иә", "Жоқ", "Жауап беру қиын"],
                },
            ],
        },
        {
            name: "feedback",
            title: "Сіздің пікірлеріңіз",
            elements: [
                {
                    type: "comment",
                    name: "Комментарий",
                    title: "Сіздің ескертулеріңіз, тілектеріңіз, ұсыныстарыңыз",
                    rows: 4,
                },
            ],
        },
    ],
};
